version: '3.5'
services:
#Services
 nginx:
  build:
    context: build
    args:
     ENVPATH: nginx.env
  hostname: nginx
  privileged: true
  networks:
   perimetral_ext:
    ipv4_address: 192.168.200.202
  volumes:
   - nginx:/etc/nginx
networks:
  perimetral_ext:
    external: true
volumes:
 nginx:
