version: '3.5'
services:
#Services
# zentyal:
#  build:
#    context: build
#    args:
#     ENVPATH: zentyal.env
#  hostname: zentyal
#  privileged: true
#  tmpfs:
#   - /run
#   - /run/lock
#   - /tmp
#  volumes:
#   - /sys/fs/cgroup:/sys/fs/cgroup:ro
#   - /lib/modules:/lib/modules
#  networks:
#   zentyal:
#    ipv4_address: 192.168.51.100
 hostlan1:
  build:
    context: build
    args:
     ENVPATH: hostlan1.env
  hostname: hostlan1
  privileged: true
  networks:
   lan1:
    ipv4_address: 192.168.52.2
 hostlan2:
  build:
    context: build
    args:
     ENVPATH: hostlan2.env
  hostname: hostlan2
  privileged: true
  networks:
   lan2:
    ipv4_address: 172.101.10.2
networks:
  lan1:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: zentyal_lan1
    ipam:
     config:
       - subnet: 192.168.52.0/24
  lan2:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: zentyal_lan2
    ipam:
     config:
       - subnet: 172.101.10.0/24
