version: '3.5'
services:
#Services
 wordpress:
  build:
    context: build
    args:
     ENVPATH: wordpress.env
  hostname: wordpress
  networks:
   wp:
  depends_on:
   - mysql
  ports:
  - "8080:80"
  - "8043:443"
 mysql:
  build:
    context: build
    args:
     ENVPATH: mysql.env
  hostname: mysql
  networks:
   wp:
    ipv4_address: 192.168.50.100
  volumes:
   - fortimysql:/var/lib/mysql
networks:
  wp:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: npm_forti
    ipam:
     config:
       - subnet: 192.168.50.0/24
volumes:
 fortimysql:
