version: '3.5'
services:
#Services
 wordpress:
  build:
    context: build
    args:
     ENVPATH: wordpress.env
  hostname: wordpress
  privileged: true
  networks:
   wp:
    ipv4_address: 192.168.50.2
  depends_on:
   - mysql
 mysql:
  build:
    context: build
    args:
     ENVPATH: mysql.env
  hostname: mysql
  privileged: true
  networks:
   wp:
    ipv4_address: 192.168.50.100
  volumes:
   - fortimysql:/var/lib/mysql
 hack:
  build:
    context: build
    args:
     ENVPATH: hack.env
  hostname: hack
  privileged: true
  networks:
   wp:
    ipv4_address: 192.168.50.99
networks:
  wp:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: wp_forti
    ipam:
     config:
       - subnet: 192.168.50.0/24
volumes:
 fortimysql:
