services:
#Services
 zabbix:
  build:
    context: build
    args:
     ENVPATH: zabbix.env
  hostname: zabbix
  networks:
   zabbix:
    ipv4_address: 192.168.62.100
 zabapache:
  build:
    context: build
    args:
     ENVPATH: zabapache.env
  hostname: zabapache
  networks:
   zabbix:
    #ipv4_address: 192.168.62.10
 zabmysql:
  build:
    context: build
    args:
     ENVPATH: zabmysql.env
  hostname: zabmysql
  networks:
   zabbix:
networks:
  zabbix:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: zabbix_forti
    ipam:
     config:
       - subnet: 192.168.62.0/24

